### ISSUE TITLE
Prettify the wires

### ISSUE THREAD

**Issue by timurglobal** [ladybug-tools/ladybug-legacy#204]
Hey Mostapha.

Awesome plugin!!!

Import weather data is in a way the main ("boss") component, so one ought to think that aligning other components' inputs with Import weather data's outputs is a nice and tidy way of managing the wires (or at least keeping everything nice and clean).

(Same logic should also apply to other components as well in this weird component "food chain")

P.S. My first time, how was it? I hope it doesn't sound rude, somehow I feel that I sound rude sometimes))

**Comment by mostaphaRoudsari** [comment]
Hi @timurglobal, Thanks. Yes. It looks good. I'm adding the image that you sent on Grasshopper group which make it more clear.

![](http://api.ning.com/files/GHjisZ0-*yRj1ZjHkJJfOPM-rFfb3xKf2AXQ0iq34zmr82RNzowE5kR0bLU3yGLgWicMwDWyy7-xATeTjOrNZf7zjMWVJjkP/Whyyyyy.png)

This is an easy fix from our side but it can cause issues for users who use update component to updated their files. Update component doesn't update input/output names and because of that if a user use update component and not drag the component from the tab, they will get the results reversed. Once we add the check for inputs/outputs to the updated component we will also address this issue.

**Comment by timurglobal** [comment]
Thank you, my (and maybe someone else's) eyes will finally rest XD

**Comment by AntoineDao** [comment]
I removed @mostaphaRoudsari 's assignment as this issue is 3 years old.

**Comment by mostaphaRoudsari** [comment]
Making this change will break people's workflow. As the tag says this change should be considered for ladybug[+] plugin.
