### ISSUE TITLE
Moving this repository to ladybug-tools organization

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-tools/ladybug-legacy#469]
We are moving this repository to ladybug-tools organization: https://github.com/ladybug-tools/ so we can add the issues to `hacktoberfest`.

This will break the update components! I will send a fix after the migration and update [this example](http://hydrashare.github.io/hydra/viewer?owner=mostaphaRoudsari&fork=hydra_1&id=Update_Ladybug_and_Honeybee&slide=0&scale=1&offset=0,0) on Hydra which you can use to update your installation (and the update components itself!)

cc: @antoinedao

**Comment by ayezioro** [comment]
Hi @mostaphaRoudsari,
Just posted a new issue that somehow get lost (i don't see it). The issue is regarding the updater components, which are not working. Now i see why.
Will wait for your update on this. Just can tell you that those that will use those, until the fix is on, can have 2 situations:
1. No input for the sourceDirectory: Red component. Don't work.
2. input for the sourceDirectory: Deletes all ghuser files and empties the directories where they were.
Happened to me today ... :-)

Thanks,
-A.

**Comment by mostaphaRoudsari** [comment]
That is expected! :| I'm fixing it now and will send a reply here:

https://discourse.ladybug.tools/t/update-component-error-ini-object-is-not-iterable/7273

**Comment by mostaphaRoudsari** [comment]
Done! See the fix here:

https://discourse.ladybug.tools/t/update-component-error-ini-object-is-not-iterable/7273/2

**Comment by ayezioro** [comment]
Great. Thanks!!
Life is timing, and mine in this case was not good ... :-)
-A.
