### ISSUE TITLE
Ladybug: How to change the temperature legends from C to °C.

### ISSUE THREAD

**Issue by Maximilian16061996** [ladybug-tools/ladybug-legacy#474]
Hello guys,

I have the following problem: I would like to set up a file in which I can visualize the temperature with a chart in Ladybug. However the legends of all the different chart types always use "C" as head of the legend. I would like to change this to "°C". Any idea how I can do that?

Looking forward to hearing from you!
Best Max

**Comment by devngc** [comment]
You can do the following to achieve what you mentioned.
![Custom Legend](https://user-images.githubusercontent.com/20086924/73457812-4273a880-4342-11ea-948a-90d71f18f319.png)
Using this [File](https://github.com/devngc/Work-in-Progress/tree/master/Ladybug%20Help%20Samples)
Please close this issue if this answers your query.

**Comment by chriswmackey** [comment]
It's also worth adding that, because the degree symbol isn't an ASCII character, it can create issues on certain machines that lack a full character set and, perhaps more importantly, it creates issues with simulation engines like EnergyPlus, which halts the whole simulation when it finds a non-ASCII character. So this is why the software is the way that it is and it's why we still plan to use `C` in the [+] libraries (without the degree symbol). But we'll make sure that there are always workarounds like this if you need them.
