### ISSUE TITLE
Area difference between ladybug componets and Grasshopper for nonplanar meshes

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-tools/ladybug-legacy#75]
Looks like a tolerance issue. Reported by  Diederik

![areadifference](https://cloud.githubusercontent.com/assets/2915573/3743022/794d7384-1771-11e4-9121-ef34e28274c5.png)

**Comment by chriswmackey** [comment]
This issue is closely related to this one:
https://github.com/mostaphaRoudsari/ladybug/issues/167

**Comment by chriswmackey** [comment]
From what I can tell, Ladybug is still correct.  I am guessing that the manner in which those non-native GH components are exploding and calculating the area of the mesh faces is not how you are supposed to do it (perhaps they are exploding the quad faces into triangles?) @mostaphaRoudsari , please confirm this if you can.

**Comment by mostaphaRoudsari** [comment]
I didn't get a chance o compare the results so I can't tell. A logical approach is to do a side by side comparison and find the faces with different areas and use a third method to figure out which one is the most accurate.
I assume the issue happens when Ladybug reconstruct mesh faces and some of them end up being different from the original non-planar mesh faces. This is just a guess until someone can put the numbers side by side.

**Comment by devngc** [comment]
@mostaphaRoudsari, @chriswmackey,
Is this a high priority? This is tagged as a bug. I can look into this.

**Comment by chriswmackey** [comment]
@devngc ,

I think this one might be an issue that's not easily solve-able with a fix since a non-planar quad face in a mesh inherently has an ambiguous area. In traditional definitions of meshes, all quad faces are interpreted as two triangles (I think this is what Rhino does when you get the mesh area). So, in this sense, the area of a non-planar quad face is the summed area of those two triangles. But under the hood in ladybug, we cast all mesh faces to breps and so the face area gets interpreted as the area of the interpolated surface between the points instead of the area of two triangles.

I think our interpretation in ladybug is probably more accurate in most situations but, as I mentioned, the definition of a non-planar quad face area is ambiguous so it's up to interpretation. Maybe a more compelling reason for why we should not change our approach is that, if people increase the resolution of the analysis (using a smaller grid size), this difference between these two values should get smaller and smaller. So I think we just chalk this issue up to the ambiguity introduced by approximating a curved surface as a mesh.

**Comment by devngc** [comment]
Thanks for sharing that @chriswmackey. In that case, I believe it is safe to close this issue.

**Comment by chriswmackey** [comment]
Yes, let's do it!
